// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "test1",
    id: "830c1226-c0c3-41cf-ad4c-fc73030d7a1b",
    method: "POST",
    address: "https://reqres.in/api/users",
    data: '{\r\n    "name": "lotfi",\r\n    "job": "leader"\r\n}',
    post(response) {
      let test1_ok = true;
      pm.test("Status code is 201", function() {
        if (pm.response.code !== 201) {
          test1_ok = false;
        }
        pm.response.to.have.status(201);
      });

      pm.test("verfication valeurs", () => {
        let rep = pm.response.json();
        if (rep.name !== "lotfi") {
          test1_ok = false;
        }
        pm.expect(rep.name).to.be.eql("lotfi2");
      });
      console.log(test1_ok);
      pm.environment.set("test1_ok", test1_ok);
    }
  });

  postman[Request]({
    name: "test2",
    id: "3eeee251-1fdf-4afb-8b7f-d97c2835ecc1",
    method: "GET",
    address: "https://reqres.in/api/users/2",
    post(response) {
      let test2_ok = true;
      pm.test("Status code is 200", function() {
        if (pm.response.code !== 200) {
          test2_ok = false;
        }
        pm.response.to.have.status(200);
      });
      pm.environment.set("test2_ok", test2_ok);
    }
  });
}
